/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ChatRecord: typeof import('./src/components/record/ChatRecord.vue')['default']
    CommonChart: typeof import('./src/components/chart/CommonChart.vue')['default']
    EntryRecord: typeof import('./src/components/record/EntryRecord.vue')['default']
    GiftRecord: typeof import('./src/components/record/GiftRecord.vue')['default']
    GuardRecord: typeof import('./src/components/record/GuardRecord.vue')['default']
    HeaderBar: typeof import('./src/components/bar/HeaderBar.vue')['default']
    HeatMap: typeof import('./src/components/chart/HeatMap.vue')['default']
    IBxsChat: typeof import('~icons/bxs/chat')['default']
    IBxsHome: typeof import('~icons/bxs/home')['default']
    IBxsMoon: typeof import('~icons/bxs/moon')['default']
    IBxsObjectsVerticalBottom: typeof import('~icons/bxs/objects-vertical-bottom')['default']
    IBxsSun: typeof import('~icons/bxs/sun')['default']
    IBxsUser: typeof import('~icons/bxs/user')['default']
    InteractionAllFilter: typeof import('./src/components/filter/InteractionAllFilter.vue')['default']
    InteractionBaseFilter: typeof import('./src/components/filter/InteractionBaseFilter.vue')['default']
    InteractionChatFilter: typeof import('./src/components/filter/InteractionChatFilter.vue')['default']
    InteractionEntryFilter: typeof import('./src/components/filter/InteractionEntryFilter.vue')['default']
    InteractionGiftFilter: typeof import('./src/components/filter/InteractionGiftFilter.vue')['default']
    InteractionGuardFilter: typeof import('./src/components/filter/InteractionGuardFilter.vue')['default']
    InteractionMessageFilter: typeof import('./src/components/filter/InteractionMessageFilter.vue')['default']
    InteractionTable: typeof import('./src/components/table/InteractionTable.vue')['default']
    ITdesignJump: typeof import('~icons/tdesign/jump')['default']
    LiveInfoCard: typeof import('./src/components/card/LiveInfoCard.vue')['default']
    MedalChip: typeof import('./src/components/chip/MedalChip.vue')['default']
    MessageRecord: typeof import('./src/components/record/MessageRecord.vue')['default']
    PrivilegeAvatar: typeof import('./src/components/circle/PrivilegeAvatar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatisticPeriodTable: typeof import('./src/components/table/StatisticPeriodTable.vue')['default']
    StatisticSessionTable: typeof import('./src/components/table/StatisticSessionTable.vue')['default']
    UserDetailTable: typeof import('./src/components/table/UserDetailTable.vue')['default']
    UserInfoCard: typeof import('./src/components/card/UserInfoCard.vue')['default']
    UserInteractionCard: typeof import('./src/components/card/UserInteractionCard.vue')['default']
    UserInteractionFilter: typeof import('./src/components/filter/UserInteractionFilter.vue')['default']
    UserInteractionModal: typeof import('./src/components/modal/UserInteractionModal.vue')['default']
    UserTopCard: typeof import('./src/components/card/UserTopCard.vue')['default']
    UserTopTable: typeof import('./src/components/table/UserTopTable.vue')['default']
  }
}
