/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AwardRecord: typeof import('./../components/record/AwardRecord.vue')['default']
    ChatRecord: typeof import('./../components/record/ChatRecord.vue')['default']
    CommonChart: typeof import('./../components/chart/CommonChart.vue')['default']
    EntryRecord: typeof import('./../components/record/EntryRecord.vue')['default']
    GiftRecord: typeof import('./../components/record/GiftRecord.vue')['default']
    GuardRecord: typeof import('./../components/record/GuardRecord.vue')['default']
    HeaderBar: typeof import('./../components/bar/HeaderBar.vue')['default']
    HeatMap: typeof import('./../components/chart/HeatMap.vue')['default']
    IBxsChat: typeof import('~icons/bxs/chat')['default']
    IBxsHome: typeof import('~icons/bxs/home')['default']
    IBxsInfoCircle: typeof import('~icons/bxs/info-circle')['default']
    IBxsMoon: typeof import('~icons/bxs/moon')['default']
    IBxsObjectsVerticalBottom: typeof import('~icons/bxs/objects-vertical-bottom')['default']
    IBxsSun: typeof import('~icons/bxs/sun')['default']
    IBxsUser: typeof import('~icons/bxs/user')['default']
    IClarityPasteLine: typeof import('~icons/clarity/paste-line')['default']
    ICodiconGraphLine: typeof import('~icons/codicon/graph-line')['default']
    InteractionAllFilter: typeof import('./../components/filter/InteractionAllFilter.vue')['default']
    InteractionAwardFilter: typeof import('./../components/filter/InteractionAwardFilter.vue')['default']
    InteractionBaseFilter: typeof import('./../components/filter/InteractionBaseFilter.vue')['default']
    InteractionChatFilter: typeof import('./../components/filter/InteractionChatFilter.vue')['default']
    InteractionEntryFilter: typeof import('./../components/filter/InteractionEntryFilter.vue')['default']
    InteractionGiftFilter: typeof import('./../components/filter/InteractionGiftFilter.vue')['default']
    InteractionGuardFilter: typeof import('./../components/filter/InteractionGuardFilter.vue')['default']
    InteractionMessageFilter: typeof import('./../components/filter/InteractionMessageFilter.vue')['default']
    InteractionTable: typeof import('./../components/table/InteractionTable.vue')['default']
    ITdesignJump: typeof import('~icons/tdesign/jump')['default']
    LiveInfoCard: typeof import('./../components/card/LiveInfoCard.vue')['default']
    MedalChip: typeof import('./../components/chip/MedalChip.vue')['default']
    MessageRecord: typeof import('./../components/record/MessageRecord.vue')['default']
    PrivilegeAvatar: typeof import('./../components/circle/PrivilegeAvatar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatisticLiveModal: typeof import('./../components/modal/StatisticLiveModal.vue')['default']
    StatisticPeriodTable: typeof import('./../components/table/StatisticPeriodTable.vue')['default']
    StatisticSessionTable: typeof import('./../components/table/StatisticSessionTable.vue')['default']
    UserAwardCard: typeof import('./../components/card/UserAwardCard.vue')['default']
    UserDetailTable: typeof import('./../components/table/UserDetailTable.vue')['default']
    UserInfoCard: typeof import('./../components/card/UserInfoCard.vue')['default']
    UserInteractionCard: typeof import('./../components/card/UserInteractionCard.vue')['default']
    UserInteractionFilter: typeof import('./../components/filter/UserInteractionFilter.vue')['default']
    UserInteractionModal: typeof import('./../components/modal/UserInteractionModal.vue')['default']
    UserSearchTable: typeof import('./../components/table/UserSearchTable.vue')['default']
    UserTopCard: typeof import('./../components/card/UserTopCard.vue')['default']
    UserTopTable: typeof import('./../components/table/UserTopTable.vue')['default']
    UserWordCloudCard: typeof import('./../components/card/UserWordCloudCard.vue')['default']
    WordCloud: typeof import('./../components/chart/WordCloud.vue')['default']
  }
}
